import { EntityConstants } from './entity-constants';

export const FAVORITE_CONSTANTS: EntityConstants = {
  TABLE_NAME: 'favorites',
  IDENTIFIER: '_id',
  FIELD_NAMES: [
    'title',
    'seriesUrl',
    'type',
    'actors',
    'intro',
    'image',
    'sourceId',
    'sourceName',
    'createTime',
    'episodeUpdateTime',
    'episodeUpdateFlag',
    'lastWatchTime',
    'seek',
    'currEpisodeSource',
    'currEpisode',
  ],
  FIELDS: {
    TITLE: 'title',
    SERIES_URL: 'seriesUrl',
    TYPE: 'type',
    ACTORS: 'actors',
    INTRO: 'intro',
    IMAGE: 'image',
    SOURCE_ID: 'sourceId',
    SOURCE_NAME: 'sourceName',
    CREATE_TIME: 'createTime',
    EPISODE_UPDATE_TIME: 'episodeUpdateTime',
    EPISODE_UPDATE_FLAG: 'episodeUpdateFlag',
    LAST_WATCH_TIME: 'lastWatchTime',
    SEEK: 'seek',
    CURR_EPISODE_SOURCE: 'currEpisodeSource',
    CURR_EPISODE: 'currEpisode',
  },
};
